name: Atualizar Jogadores

on:
  schedule:
    - cron: "*/5 * * * *"  # Executa a cada 10 minutos

  workflow_dispatch:  # Permite rodar manualmente

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Chamar API de atualização
        run: curl -X GET "https://duolingo-challeng.onrender.com/jogadores"
